package mining

import akka.actor.{Actor, ActorRef, Cancellable, Stash}
import akka.pattern.{ask, pipe}
import akka.util.Timeout
import com.redbottledesign.bitcoin.rpc.stratum.message.ResultFactory
import com.redbottledesign.bitcoin.rpc.stratum.transport.tcp.StratumTcpServerConnection
import mining.MiningMessages._
import org.bouncycastle.util.encoders.Hex
import org.slf4j.{Logger, LoggerFactory}
import stratum.message.{Announcement, Response}

import java.math.BigDecimal
import java.net.InetSocketAddress
import java.util.Arrays
import javax.inject.Inject
import scala.concurrent.duration._
import scala.language.postfixOps
import scala.util.{Failure, Success, Try}

/**
 * Per-miner-connection actor.
 *
 * Each time a miner opens a TCP connection, MiningStratumServer creates one of
 * these actors and passes it a reference to the underlying JStratum connection
 * object.  All Stratum protocol handling (subscribe / authorize / submit) is
 * implemented here; the actor communicates with LithosPool (and, via forwarding,
 * with LithosJobManager) for everything that requires shared state.
 *
 * Design notes
 * ────────────
 *  • The JStratum connection object is NOT available at actor-creation time
 *    because of the chicken-and-egg dependency between the connection state
 *    (which needs the actor ref) and this actor (which needs the connection).
 *    MiningStratumServer resolves this by sending ConnectionEstablished as the
 *    very first message, before any I/O threads are started.  Until that
 *    message is received, all other messages are stashed.
 *
 *  • All calls to connection.sendResponse are wrapped in safeResponse so that
 *    a closed socket never crashes the actor.
 *
 *  • Share processing is driven via ask + pipeTo so the actor mailbox is never
 *    blocked.  In-flight async results are tagged with the original Stratum
 *    request ID so the miner gets the correct response even under load.
 *
 * @param subscriptionId   Unique subscription token generated by MiningStratumServer
 * @param socketAddress    Remote address of the miner
 * @param poolActor        LithosPool reference (also routes to LithosJobManager via forward)
 * @param connectionId     Stable ID used to deregister from LithosPool on disconnect
 */
class StratumConnection(subscriptionId: String,
                        socketAddress: InetSocketAddress,
                        poolActor: ActorRef,
                        connectionId: String)
  extends Actor with Stash {

  import StratumConnection._
  import context.dispatcher

  private val logger: Logger = LoggerFactory.getLogger(s"StratumConnection[$connectionId]")
  implicit private val defaultTimeout: Timeout = Timeout(5.seconds)

  // ─── mutable state set after ConnectionEstablished ────────────────────────
  private var connection: StratumTcpServerConnection = _
  private var extraNonce1: Option[String]            = None
  private var currentJob: Option[stratum.BlockTemplate] = None

  // Periodic liveness check so the actor self-terminates when the socket closes
  private val livenessTicker: Cancellable =
    context.system.scheduler.scheduleWithFixedDelay(10.seconds, 10.seconds, self, CheckLiveness)(
      context.dispatcher
    )

  override def postStop(): Unit = {
    livenessTicker.cancel()
    poolActor ! MinerDisconnected(connectionId)
  }

  // ─── receive: waiting for the connection object ────────────────────────────

  /** Initial state — stash everything until the connection reference arrives. */
  override def receive: Receive = initializing

  private def initializing: Receive = {
    case ConnectionEstablished(conn) =>
      connection = conn
      unstashAll()
      context.become(ready)
    case _ =>
      stash()
  }

  // ─── receive: normal operation ────────────────────────────────────────────

  private def ready: Receive = {

    // ── liveness ──────────────────────────────────────────────────────────
    case CheckLiveness =>
      if (!connection.isOpen) {
        logger.info(s"Connection $connectionId closed remotely, stopping actor")
        context.stop(self)
      }

    // ── broadcast from LithosPool ──────────────────────────────────────────
    case BroadcastJob(template) =>
      currentJob = Some(template)
      safeResponse(connection.sendResponse(Announcement.miningJob(template)))

    // ── Stratum subscribe ─────────────────────────────────────────────────
    // Ask LithosJobManager (via LithosPool.forward) for a fresh extraNonce1
    // and the current job, then send all three subscribe responses at once.
    case MinerSubscribe(requestId) =>
      (poolActor ? RequestSubscription)
        .mapTo[SubscriptionData]
        .map(data => SubscriptionReady(requestId, data))
        .pipeTo(self)

    case SubscriptionReady(requestId, data) =>
      extraNonce1 = Some(data.extraNonce1)
      safeResponse(
        connection.sendResponse(
          Response.subscribe(requestId, subscriptionId, data.extraNonce1, data.extraNonce2Size)
        )
      )
      safeResponse(connection.sendResponse(Announcement.difficulty(BigDecimal.ONE)))
      data.currentJob.foreach { job =>
        currentJob = Some(job)
        safeResponse(connection.sendResponse(Announcement.miningJob(job)))
      }

    // ── Stratum authorize ─────────────────────────────────────────────────
    // Always accepts.  Mirrors ErgoConnectionState behaviour.
    case MinerAuthorize(requestId, workerName, _) =>
      logger.info(s"Authorizing worker '$workerName' on connection $connectionId")
      safeResponse(connection.sendResponse(Response.authorize(requestId, true, null)))

    // ── Stratum submit ────────────────────────────────────────────────────
    case MinerSubmit(requestId, workerName, jobId, en2Hex, nTime, en1Hex) =>
      extraNonce1 match {
        case None =>
          safeResponse(connection.sendResponse(Response.submit(requestId, null, "25: not subscribed")))

        case Some(_) =>
          val shareMsg = ProcessShare(
            jobId      = jobId,
            difficulty = java.math.BigInteger.ONE,
            extraNonce1 = Arrays.copyOfRange(Hex.decode(en1Hex), 0, 4),
            extraNonce2 = Hex.decode(en2Hex),
            nTime      = nTime,
            ipAddress  = socketAddress.getHostString,
            port       = socketAddress.getPort,
            workerName = workerName
          )
          (poolActor ? shareMsg)
            .mapTo[ShareResult]
            .map(result => ShareProcessed(requestId, result))
            .pipeTo(self)
      }

    // ── share result from LithosJobManager (piped back to self) ────────────
    case ShareProcessed(requestId, result) =>
      result match {
        case accepted: ShareAccepted =>
          safeResponse(
            connection.sendResponse(Response.submit(requestId, trueResult, null))
          )
          // Notify LithosPool if this share requires pool-level action
          if (accepted.isBlock || accepted.isSuperShare) {
            poolActor ! accepted
          }

        case ShareRejected(id, msg, rejectedNonce1) =>
          id match {
            case 21 =>
              // Potentially stale job — we still accept the share and push the
              // latest job so the miner can resume immediately
              logger.warn(s"Potentially stale share from ${workerName(requestId)} on connection $connectionId")
              safeResponse(connection.sendResponse(Response.submit(requestId, trueResult, null)))
              currentJob.foreach(job => safeResponse(connection.sendResponse(Announcement.miningJob(job))))

            case 22 =>
              // Duplicate nonce: if it's OUR extraNonce1 that caused it, rotate
              // to a fresh one exactly as the Java version does
              logger.warn(s"Duplicate share from ${workerName(requestId)} on connection $connectionId")
              if (Hex.toHexString(rejectedNonce1).equalsIgnoreCase(extraNonce1.getOrElse(""))) {
                (poolActor ? RequestSubscription)
                  .mapTo[SubscriptionData]
                  .map(data => NonceRotation(requestId, data))
                  .pipeTo(self)
              } else {
                logger.warn(s"Duplicate nonce1 ${Hex.toHexString(rejectedNonce1)} already handled, skipping rotation")
                safeResponse(connection.sendResponse(Response.submit(requestId, trueResult, null)))
              }

            case _ =>
              logger.error(s"Share error $id: $msg from connection $connectionId")
              safeResponse(
                connection.sendResponse(Response.submit(requestId, null, s"$id: $msg"))
              )
          }
      }

    // ── extraNonce1 rotation after a duplicate-nonce collision ────────────
    case NonceRotation(requestId, data) =>
      extraNonce1 = Some(data.extraNonce1)
      logger.info(s"Rotating extraNonce1 to ${data.extraNonce1} on connection $connectionId")
      safeResponse(
        connection.sendResponse(
          Announcement.extraNonce1(data.extraNonce1, data.extraNonce2Size)
        )
      )
      currentJob.foreach(job => safeResponse(connection.sendResponse(Announcement.miningJob(job))))
      safeResponse(connection.sendResponse(Response.submit(requestId, trueResult, null)))

    // ── Akka plumbing failures ─────────────────────────────────────────────
    case Failure(ex) =>
      logger.error(s"Async operation failed on connection $connectionId", ex)
  }

  // ─── helpers ──────────────────────────────────────────────────────────────

  /** Executes a sendResponse call, logging but not crashing on I/O errors. */
  private def safeResponse(block: => Unit): Unit =
    Try(block).failed.foreach { ex =>
      logger.warn(s"Failed to send response on connection $connectionId: ${ex.getMessage}")
    }

  /** Lazy stand-in for `workerName` in log messages where we only have a requestId. */
  private def workerName(requestId: String): String = s"worker@$connectionId"

  /** Pre-built TRUE result to avoid repeated factory calls. */
  private lazy val trueResult =
    ResultFactory.getInstance().createResult(java.lang.Boolean.TRUE)
}

object StratumConnection {
  // ─── internal async messages (never appear in MiningMessages) ─────────────

  /**
   * Sent by MiningStratumServer to the actor immediately after creation,
   * before JStratum's I/O threads are started.
   */
  case class ConnectionEstablished(connection: StratumTcpServerConnection)

  /** Piped back to self once LithosJobManager replies to RequestSubscription. */
  private case class SubscriptionReady(requestId: String, data: SubscriptionData)

  /** Piped back to self once LithosJobManager replies to ProcessShare. */
  private case class ShareProcessed(requestId: String, result: ShareResult)

  /** Piped back to self after a fresh extraNonce1 is obtained following a duplicate. */
  private case class NonceRotation(requestId: String, data: SubscriptionData)

  /** Periodic self-message to check whether the underlying socket is still alive. */
  private case object CheckLiveness
}
